/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CustomerDto } from '../models/models';


import { Configuration }                                     from '../configuration';



export interface CustomerControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     *
     *
     * @param customerDto
     */
    createCustomer(customerDto: CustomerDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     *
     *
     * @param id
     */
    deleteCustomer(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     *
     *
     * @param id
     */
    getCustomer(id: number, extraHttpRequestParams?: any): Observable<CustomerDto>;

    /**
     *
     *
     */
    getCustomers(extraHttpRequestParams?: any): Observable<Array<CustomerDto>>;

    /**
     *
     *
     * @param id
     * @param customerDto
     */
    updateCustomer(id: number, customerDto: CustomerDto, extraHttpRequestParams?: any): Observable<{}>;

}
