/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { RentalDto } from '../models/models';


import { Configuration }                                     from '../configuration';



export interface RentalControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     *
     *
     * @param rentalDto
     */
    createRental(rentalDto: RentalDto, extraHttpRequestParams?: any): Observable<{}>;

    /**
     *
     *
     * @param id
     */
    deleteRental(id: number, extraHttpRequestParams?: any): Observable<{}>;

    /**
     *
     *
     * @param id
     */
    getRental(id: number, extraHttpRequestParams?: any): Observable<RentalDto>;

    /**
     *
     *
     */
    getRentals(extraHttpRequestParams?: any): Observable<Array<RentalDto>>;

    /**
     *
     *
     * @param id
     * @param rentalDto
     */
    updateRental(id: number, rentalDto: RentalDto, extraHttpRequestParams?: any): Observable<{}>;

}
