/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RentalDto { 
    rentalId?: number;
    carId?: number;
    carLicensePlate?: string;
    carBrandAndModel?: string;
    customerId?: number;
    customerFullName?: string;
    customerEmail?: string;
    rentalBegin?: string;
    rentalEnd?: string;
    returnDate?: string;
    mileageBegin?: number;
    mileageEnd?: number;
    description?: string;
    createdWhen?: string;
}

